### ISSUE TITLE
How to get "st-chat/examples/chatbot.py" running ?

### ISSUE THREAD

**Issue by sergey-ivanchuk** [AI-Yash/st-chat#12]
Would like to have `examples/chatbot.py`running locally on computer

Running `streamlit run  chatbot.py` in terminals leads to --

```text
KeyError: 'generated_text'
Traceback:
File "/opt/anaconda3/envs/st-chat/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
File "/Users/sivanchu/Documents/GitHub/st-chat/examples/chatbot.py", line 43, in <module>
    st.session_state.generated.append(output["generated_text"])
```

Full sequence of code --

```bash
conda create -y -n st-chat  python=3.8 
conda activate st-chat
pip install streamlit-chat 
streamlit run  examples/chatbot.py
```

**Comment by sergey-ivanchuk** [comment]
Update --

I resolved my issue.

After some printing and logging, I needed this change --

`headers = {"Authorization": "Bearer st.secrets['api_key']"}`

`Bearer` might be the new needed syntax for  https://github.com/AI-Yash/st-chat/blob/8ac13aa3fdf98bacb971f24c759c3daa16669183/examples/chatbot.py#L11

**Comment by aurotripathy** [comment]
The above was very  helpful @sergey-ivanchuk .
Thank you.
How do you create the secret file?
I jammed the API key in the file itself for the app to work.

**Comment by sergey-ivanchuk** [comment]
make sure you have this file -- `.streamlit/secrets.toml` .... it should be in the root of your app repo
