### ISSUE TITLE
How to show audio component

### ISSUE THREAD

**Issue by paulocoutinhox** [AI-Yash/st-chat#16]
Hi,

Im trying to show audio component but nothing works.

I tried:

```
st.session_state.history.append({"message": st.audio(audio_bytes, format='audio/mp3'), "is_user": True, "key":str(uuid.uuid4())})
```

And:

```
st.session_state.history.append({"message": '<audio controls src="audio.mp3"></audio>', "is_user": True, "key":str(uuid.uuid4())})
```

The HTML show as text.

How to make it work?

**Comment by 0toshigami** [comment]
I've create a pull request #24 to make it work. Here is an example
![image](https://user-images.githubusercontent.com/27276267/224220742-3fa9ca38-5352-4291-98ad-3843188af152.png)
