### ISSUE TITLE
Change message order not possible

### ISSUE THREAD

**Issue by bazylhorsey** [AI-Yash/st-chat#17]
```
if st.session_state['generated']:
    for i in range(len(st.session_state['generated'])-1, -1, 1):
        message(st.session_state['past'][i], is_user=True, key=str(i) + '_user', avatar_style='personas')
        message(st.session_state['generated'][i], key=str(i), avatar_style='identicon')
```

Using a positive step in the messages should be possible. However, it stays one behind if using a positive step (1),
The library seems to only work if step on the for loop is set to -1.

**Comment by yashppawar** [comment]
Sorry I didn't get what you mean, if you mean the step value in the range(), then it has nothing to do with this library, streamlit-chat is just a UI component, you might want to look at how the data is stored in the `session_state`
