### ISSUE TITLE
Image Display

### ISSUE THREAD

**Issue by Kashif-Raza6** [AI-Yash/st-chat#38]
Is there any way to display the images in chat format. I am trying to display the image with 
` message(st.session_state["generated"][i], key=str(i), avatar_style="thumbs")` but its displaying the error.

**Comment by yashppawar** [comment]
Combined with [streamlit static serving](https://docs.streamlit.io/library/advanced-features/static-file-serving) and latest version of streamlit-chat (supporting html & markdown), it is now possible

```py
from streamlit_chat import message

# local image stored in the static folder, see static file serving (advanced features, streamlit)
message('![cat image](/app/static/cat.jpg)')
```
