### ISSUE TITLE
Can chat show dataframes or plots as responses?

### ISSUE THREAD

**Issue by cosmosanalytics** [AI-Yash/st-chat#39]
See yolopandas https://github.com/ccurme/yolopandas, the responses from chatbot are either dataframes or plots. How to use streamlit chat to show chatbot responses of dataframes and plots? 

![image](https://github.com/AI-Yash/st-chat/assets/100080151/35b263ca-a889-4633-a8b2-79f00d280f79)

**Comment by cosmosanalytics** [comment]
Also how to show the code even when I set yolo=True?

**Comment by cosmosanalytics** [comment]
I can only put the plot on top the chat record, not in the record. It would be great there is a way to embed plots in the chat record.
![image](https://github.com/AI-Yash/st-chat/assets/100080151/6dbd944e-69de-4fcb-8628-6edf608f3ae8)

**Comment by yashppawar** [comment]
not sure about data frames yet, but you can save the plot as an image, in the static folder and then Combine it with [streamlit static serving](https://docs.streamlit.io/library/advanced-features/static-file-serving) and the latest version of streamlit-chat (supporting HTML & markdown), it can be done

```py
from streamlit_chat import message

# generate plot
plot_path = 'static/plot.png'
plt.savefig(plot_path) 
# local image stored in the static folder, see static file serving (advanced features, streamlit)
message(f'![cat image](/app/{plot_path)')
```

in case of plotly I guess you can save it as HTML, and use an Iframe to display the HTML of plot
