### ISSUE TITLE
How can I change the profile image on chat.

### ISSUE THREAD

**Issue by sooftware** [AI-Yash/st-chat#5]
Thanks for your great project!  
I want to change the profile image on chat. How can I?

**Comment by yashppawar** [comment]
Hey, sorry for late reply
you can do that easily by using the avatar_style and seed, we are using the dicebear API to get the profile picture for now, you can use any image which they provide, by providing right style and seed.
```py
message(my_message, avatar_style="avataaars", seed=123)
```
see all available styles on dicebear -> https://avatars.dicebear.com/styles

**Comment by sooftware** [comment]
Thank you !!

**Comment by subhajit2001** [comment]
How do we set the seed as you have mentioned @yashppawar

**Comment by yashppawar** [comment]
> How do we set the seed as you have mentioned @yashppawar

by changing the value for the seed parameter of `message()`
```py
message(my_message, seed=32)
message(my_message, seed=42)
```
