### ISSUE TITLE
request for removing is_user align right 

### ISSUE THREAD

**Issue by seonglae** [AI-Yash/st-chat#51]
![image](https://github.com/AI-Yash/st-chat/assets/27716524/1260c096-5e77-4255-9a16-bb54702211c1)
There is some issue for user prompt like above image (very hard to read because text-align is right)

```js
        return css`
          flex-direction: row-reverse;
          & > div {
            text-align: right;
          }
        `
```

but below fix this problem

```js
        return css`
          flex-direction: row-reverse;
        `
```

**Comment by yashppawar** [comment]
done, now there's no `text-align: right;`
