### ISSUE TITLE
How to insert markdown in the chat message() function

### ISSUE THREAD

**Issue by subhajit2001** [AI-Yash/st-chat#7]

**Comment by yashppawar** [comment]
Sorry, but it does not support markdown yet...

**Comment by subhajit2001** [comment]
Okay can you add the functionality of markdown in chat message() function

**Comment by yashppawar** [comment]
I will try to do that @subhajit2001, sorry for the inconvenience.
Academic exams are going on currently, will try to do that after exams are finished.
Cheers, 
Yash

**Comment by tushar-31093** [comment]
Hi Guys,
Any update on the markdown feature? Was trying to use GPT for content generation and for code and bullet points it does require markdown. Any ways to make it possible?

**Comment by nothans** [comment]
I am trying the same thing... st.markdown is all that it needs.
